.TH JACKMIDICLOCK "1" "May 2013" "jack_midi_clock 0.1.1" "User Commands"
.SH NAME
jack_midi_clock \- Create MIDI beat clock from JACK-Transport
.SH SYNOPSIS
.B jack_midi_clock
.SH DESCRIPTION
jack_midi_clock is a small utility which takes the time from JACK-Transport
and writes MIDI beat clock data to a dedicated JACK-MIDI port.
.PP
jack_midi_clock will send start, continue and stop messages whenever
the transport changes state.
In order for jack_midi_clock to send clock messages, a JACK timecode master
must be present and provide a tempo map (bar, beat).
.PP
jack_midi_clock runs until it receives a TERM or QUIT signal.
.SH "REPORTING BUGS"
https://github.com/x42/jack_midi_clock/issues
.br
or contact upstream directly: Gabriel M. Beddingfield <gabriel@teuton.org>
.SH COPYRIGHT
Copyright \(co 2009 Gabriel M. Beddingfield <gabriel@teuton.org>
.br
Copyright \(co 2013 Robin Gareus <robin@gareus.org>
.PP
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
